name: Rockchip-OpenWrt

on:
#  schedule:
#    - cron: 5 6 * * 0
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        
    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo
        
    - name: Free disk space
      uses: sbwml/actions@free-disk

    - name: Checkout
      uses: actions/checkout@main

    - name: Build System Setup
      uses: sbwml/actions@openwrt-build-setup

    - name: Install LLVM
      uses: sbwml/actions@install-llvm
      
    - name: Prepare Mixedwrt
      run: |
        sudo chown -R runner:runner /home/runner/work/OpenWrt-AutoBuild
        cp -r ./SCRIPTS/Rockchip/. ./SCRIPTS/
        cp -r ./SCRIPTS/. ./
        /bin/bash 01_get_ready.sh
        
    - name: Prepare Package
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        cp -r ../SCRIPTS/. ./
        /bin/bash 02_prepare_package.sh
        /bin/bash 03_custom_settings_rk.sh
        /bin/bash 04_remove_upx.sh
        
    - name: QTMDFW4
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        cp -rf ../SCRIPTS/Rockchip/config.seed .config
        
    - name: Convert Translation
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        /bin/bash 05_convert_translation.sh
        
    - name: Add ACL
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        /bin/bash 06_create_acl_for_luci.sh -a
        
    - name: Fix Permissions
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        sudo -E chmod -R 755 ./07_fix_permissions.sh
        /bin/bash 07_fix_permissions.sh
        
    - name: Make Config
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make defconfig
        
    - name: Get Architecture
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        TARGET_DEVICE_ARCH="$(grep "^CONFIG_TARGET_.*_.*=y$" ".config" | head -n 1 | sed 's/^CONFIG_TARGET_//g' | awk -F '_' '{print $1}')"
        echo "TARGET_DEVICE_ARCH=${TARGET_DEVICE_ARCH}" >>$GITHUB_ENV
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][4-9]/p' | sed -n 1p | sed 's/.tar.gz//g' | sed 's/v//g')"
        echo "latest_release=${latest_release}" >>$GITHUB_ENV
        
    - name: Cache
      uses: HiGarfield/cachewrtbuild@main
      with:
        mixkey: ${{ env.TARGET_DEVICE_ARCH }}
        prefix: ${{ github.workspace }}/openwrt
        
    - name: Make Download
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make download -j50
        
    - name: Compile Openwrt
      working-directory: ${{ github.workspace }}/openwrt
      id: compileopenwrt
      continue-on-error: true
      run: |
        make -j$(nproc)
        
    - name: If Error
      working-directory: ${{ github.workspace }}/openwrt
      if: steps.compileopenwrt.outcome == 'failure'
      run: |
        cat ./.config
        echo '================================================================'
        make -j1 V=s
        
    - name: Organize files
      id: organize
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        mv openwrt/bin/targets/rockchip/armv8/*sysupgrade.img* ./artifact/
        cd ./artifact/
        ls -Ahl
        gzip -d *.gz && exit 0
        gzip --best *.img
        ls -Ahl
        sha256sum zerowrt*m68s* | tee M68s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*m68s-plus* | tee M68s-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r66s* | tee R66s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r68s* | tee R68s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*station-p2* | tee Station-p2-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*neo3* | tee Neo3-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r2c* | tee R2c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r2c-plus* | tee R2c-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r3s* | tee R3s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r4s* | tee R4s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r4se* | tee R4se-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r5c* | tee R5c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r5s* | tee R5s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r6c* | tee R6c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*r6s* | tee R6s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*sige3* | tee Singe3-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*sige7* | tee Singe7-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*rock-5a* | tee Rock-5a-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*rock-5b* | tee Rock-5b-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*orangepi-5* | tee Orangepi-5-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        sha256sum zerowrt*orangepi-5-plus* | tee Orangepi-5-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}.sha256sum
        zip M68s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *m68s*ext4*
        zip M68s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *m68s*squashfs*
        zip M68s-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *m68s-plus*ext4*
        zip M68s-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *m68s-plus*squashfs*
        zip R66s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r66s*ext4*
        zip R66s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r66s*squashfs*
        zip R68s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r68s*ext4*
        zip R68s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r68s*squashfs* 
        zip Station-p2-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *station-p2*ext4*
        zip Station-p2-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *station-p2*squashfs* 
        zip Neo3-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *neo3*ext4*
        zip Neo3-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *neo3*squashfs* 
        zip R2c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r2c*ext4*
        zip R2c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r2c*squashfs*
        zip R2c-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r2c-plus*ext4*
        zip R2c-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r2c-plus*squashfs*
        zip R3s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r3s*ext4*
        zip R3s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r3s*squashfs*
        zip R4s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r4s*ext4*
        zip R4s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r4s*squashfs*
        zip R4se-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r4se*ext4*
        zip R4se-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r4se*squashfs*
        zip R5c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r5c*ext4*
        zip R5c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r5c*squashfs*
        zip R5s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r5s*ext4*
        zip R5s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r5s*squashfs*
        zip R6c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r6c*ext4*
        zip R6c-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r6c*squashfs*
        zip R6s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *r6s*ext4*
        zip R6s-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *r6s*squashfs*
        zip Singe3-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *sige3*ext4*
        zip Singe3-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *sige3*squashfs*
        zip Singe7-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *sige7*ext4*
        zip Singe7-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *sige7*squashfs*
        zip Rock-5a-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *rock-5a*ext4*
        zip Rock-5a-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *rock-5a*squashfs*
        zip Rock-5b-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *rock-5b*ext4*
        zip Rock-5b-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *rock-5b**squashfs* 
        zip Orangepi-5-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *orangepi-5*ext4*
        zip Orangepi-5-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *orangepi-5*squashfs*
        zip Orangepi-5-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-ext4.zip *orangepi-5-plus*ext4*
        zip Orangepi-5-plus-ZeroWrt-$(date +%Y-%m-%d)-${{ env.latest_release }}-sfs.zip *orangepi-5-plus*squashfs*
        ls -Ahl
        
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        name: OpenWRT-${{ env.latest_release }}
        allowUpdates: true
        prerelease: false
        tag: ${{ env.latest_release }}
        commit: "24.10"
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./artifact/*.zip
    - name: Print Disk Space After
      run: df -h
